# Generated by Django 4.2.7 on 2023-11-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('completed', 'completed'), ('incompleted', 'incompleted')], max_length=200),
        ),
    ]
